name: Build and Run C Programs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show repo structure
      run: |
        echo "Current directory:"
        pwd
        echo "Files:"
        ls -R

    - name: Compile C files
      run: |
        gcc -g *.c -o outDebug

    - name: Run executable
      run: |
        ./outDebug
